<?php

/**
 * @file
 * Primary module hooks for RAC Components module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function rac_components_plugin_filter_layout__layout_builder_alter(array &$definitions, array $extra) {
  // To simplify the layout builder interface, we are hiding the default layout
  // builder sections that come with Drupal.
  // Instead, we are using the 'Layout Builder Base Library' to display more
  // complex layout builder sections that are better suited to our needs.
  unset($definitions['layout_onecol']);
  unset($definitions['layout_twocol_section']);
  unset($definitions['layout_threecol_section']);
  unset($definitions['layout_fourcol_section']);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function rac_components_form_layout_builder_configure_section_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  // Advanced section.
  $form['layout_settings']['advanced']['#access'] = FALSE;
  // Background section.
  $form['layout_settings']['background_detail']['background']['#title'] = t('Background color');
  $form['layout_settings']['background_detail']['background_image']['#access'] = FALSE;
  $form['layout_settings']['background_detail']['background_image_style']['#access'] = FALSE;
  $form['layout_settings']['background_detail']['background_attachment']['#access'] = FALSE;
  $form['layout_settings']['background_detail']['background_position']['#access'] = FALSE;
  $form['layout_settings']['background_detail']['background_size']['#access'] = FALSE;
  $form['layout_settings']['background_detail']['background_overlay']['#access'] = FALSE;
  // Container section.
  $form['layout_settings']['container_detail']['container']['#title'] = t('Width');
  $form['layout_settings']['container_detail']['content_container']['#access'] = FALSE;
  // Styles section.
  $form['layout_settings']['styles']['#access'] = FALSE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function rac_components_form_layout_builder_configure_block_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  // Hide block default values such as label and whether to show the block's
  // title when adding a block in layout builder.
  $form['settings']['label_display']['#access'] = FALSE;
  $form['settings']['label_display']['#default_value'] = FALSE;
  $form['settings']['label']['#access'] = FALSE;
  if (!isset($form['settings']['label']['#default_value'])) {
    // Generate a randomish value for the required title value.
    $block_type_label = $form['settings']['block_form']['#block']->type->entity->label();
    $current_user_username = \Drupal::currentUser()->getAccountName();
    $timestamp = time();
    $form['settings']['label']['#default_value'] = "{$block_type_label} {$current_user_username} {$timestamp}";
  }
}
